In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
def int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def write_single_record(record_writer, data):
    example = tf.train.Example(features=tf.train.Features(feature={'my_var': int64_feature(data.flatten())}))
    record_writer.write(example.SerializeToString())
    
data1= np.array([1,2], np.int16)
data2 = np.array([1,2,3,4], np.int16)
compression_opt = tf.python_io.TFRecordOptions(tf.python_io.TFRecordCompressionType.GZIP)
my_writer = tf.python_io.TFRecordWriter('./test_1.tfrecord', options=compression_opt)
print('Start writing...')
write_single_record(my_writer, data1)
write_single_record(my_writer, data2)
print('Writing completed.')
my_writer.flush()
my_writer.close()
print('Closed file.')
    


In [ ]:
def parse_single_example(record):
    record_features = {
        "my_var": tf.VarLenFeature(tf.int64,),
    }
    out_data = tf.parse_single_example(serialized=record, features=record_features)
    var_data = tf.cast(out_data['my_var'], tf.int16)
    
    return var_data

dataset = tf.contrib.data.TFRecordDataset('test_1.tfrecord', "GZIP")
dataset = dataset.map(parse_single_example, num_threads=1, output_buffer_size=1)
dataset = dataset.batch(1)
batch_iterator = dataset.make_one_shot_iterator()
next_batch = batch_iterator.get_next()

with tf.Session() as sess:
    for _ in range(2):
        print(sess.run(next_batch))

In [6]:
xx = np.array([[1,2], [3,4], [5,6]], np.int8)
yy = np.array([[1,2,3], [4,9,4]], np.int8)
print(xx, xx.shape)
print(yy, yy.shape)

(array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int8), (3, 2))
(array([[1, 2, 3],
       [4, 9, 4]], dtype=int8), (2, 3))


In [7]:
xx.flatten()

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [13]:
yy.flatten()

array([1, 2, 3, 4, 9, 4], dtype=int8)

In [15]:
np.zeros(5, np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [17]:
np.concatenate((yy.flatten(), np.zeros(5, np.int8)))

array([1, 2, 3, 4, 9, 4, 0, 0, 0, 0, 0], dtype=int8)